BEGIN;

INSERT INTO topics(topic) VALUES 
('Before you Start a Social Business'),
('Starting a Social Business'),
('Running a Social Business'),
('Growing A Social Business'),
('Case Studies');

INSERT INTO questions(question, expects_yes, topic_id) VALUES 
('Have you started your social enterprise?', 'false', '1'), 
('Do you have an engaged group of people?', 'false', '2'), 
('Have you formed a legal structure?', 'false', '2'), 
('Are you bidding for contracts or seeking funding?', 'true', '2'), 
('Are you employing staff?', 'true', '2'), 
('Are you confident in your organisations governance?', 'false', '3'), 
('Do you use a form of social accounting?', 'true', '3'), 
('Do you have a skilled management?', 'false', '3'), 
('Are you looking to grow (expand, diversify etc.)?', 'true', '4'), 
('Are you thinking of connecting with like-minded groups?', 'true', '4'), 
('Do you think your idea could work in other areas?', 'true', '4'), 
('Would you like to buy another business to help you grow?', 'true', '4'), 
('Would you like to see some case studies?', 'true', '5');

INSERT INTO resources(title, description, url, topic_id, resources) VALUES 
('The Mission', 'The objective of this section is to help you write a succinct mission statement that describes your social business purpose.', 'https://businesswales.gov.wales/socialbusinesswales/mission', '1', '[{"title":"Download the Wales Co-operative Centre''s vision, mission and values statement","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Centre%20values%20mission%20vision%20v2_0.pdf"}]'), 
('Motivation', 'Ask yourself, “Why do I want to start up this social business?”  If it is for personal financial gain then you should consider setting up a sole trader business where you own it and take the profit from it.', 'https://businesswales.gov.wales/socialbusinesswales/motivation', '1', '[{"title":"Download a template to record the results of your analysis","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Motivation%20analysis%20template%20v4_0.docx"}]'), 
('Community', 'Having identified the need in the community that your social business will address, can you now describe or define that community?', 'https://businesswales.gov.wales/socialbusinesswales/community', '1', '[{"title":"Download the Community Analysis tool","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Community%20analysis%20v4_0.docx"}]'), 
('Organisational structure', '', 'https://businesswales.gov.wales/socialbusinesswales/organisational-structure', '1', '[{"title":"Organisational Structure Template","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Organisational%20Structure%20template%20v4_0.docx"},{"title":"Co-operative Values and Principles","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/The%20Co-operative%20Principles%20vSBW.pdf"}]'), 
('Who We Are', 'In this section, we focus on individual people and how they work together.', 'https://businesswales.gov.wales/socialbusinesswales/who-we-are', '1', '[{"title":"Steering Group Description","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Steering%20Group%20description%20v4_0.docx"}]'), 
('The Market', 'The market is the group of consumers that may be interested to receive your commercial products, services and social output.  It may consist of a number of smaller groups, or segments, that you need to address separately.', 'https://businesswales.gov.wales/socialbusinesswales/market', '1', '[{"title":"Market Analysis Template","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Market%20Analysis%20template%20v4_0.docx"}]'), 
('Investment', 'No business is instantly profitable.  Until it becomes profitable, your social business will require investment.  You will not be able to launch your enterprise until you have raised investment. Feasibility therefore depends upon securing investment.  However, it will be difficult to raise money before feasibility is established – a classic Catch 22 situation.', 'https://businesswales.gov.wales/socialbusinesswales/investment', '1', '[{"title":"Investment Requirement Analysis Template","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Investment%20Requirement%20Analysis%20template%20v4_0.docx"}]'), 
('Other critical factors', 'Consider your critical success factors – those things that absolutely must be in place.  For example, is the project dependent upon the acquisition of premises?  Is there a particular contract that must be in place?  Achieving these goals must be a priority for you, so what is your plan?', 'https://businesswales.gov.wales/socialbusinesswales/other-critical-factors', '1', '[{"title":"Critical Factors and Risk Analysis Template","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Critical%20Factors%20and%20Risk%20Analysis%20template%20v4_0.docx"}]'), 
('Implementation plan', 'This is the last piece of the puzzle.  Having designed your social business in enough detail to give confidence in its feasibility, you now need to demonstrate that it is actually possible to get it off the ground.', 'https://businesswales.gov.wales/socialbusinesswales/implementation-plan', '1', '[{"title":"Implementation Plan Template","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Implementation%20Plan%20template%20v4_0.docx"}]'), 
('Expansion', 'Expansion in this context is taken to mean increasing production and sales while maintaining the same general shape of the business and similar product range and customer definition. This is by far the simplest model for growth since it requires the least innovation or journey into the unknown.', 'https://businesswales.gov.wales/socialbusinesswales/expansion', '4', '[]'), 
('Diversification', 'Diversification involves looking for new opportunities outside of current products and existing customers.  Diversification is inherently more difficult than the “more of the same” option described in expansion because it involves developing and delivering products or services outside of the existing “comfort zone”.', 'https://businesswales.gov.wales/socialbusinesswales/diversification', '4', '[]'), 
('Consortia Working', 'One way in which a business can develop its revenue, profitability and standing and also reduce its cost base is to establish consortia with other businesses.', 'https://businesswales.gov.wales/socialbusinesswales/consortia-working', '4', '[]'), 
('Spin-outs', 'It is worth considering that there might be more than one enterprise bound up in the existing Social Business and it may be possible to create two – or more – Social Businesses that would find it both easier to manage themselves, raise investment, increase capacity and focus resources on providing an “offer” that is simpler to explain in the market place.', 'https://businesswales.gov.wales/socialbusinesswales/spin-outs', '4', '[]'), 
('Mergers and Acquisition', 'Mergers and acquisitions might sound predatory and not the sort of process undertaken by a Social Business but there are situations in which it might be worthy of consideration as a growth strategy. For example, if another business operating in your market-place becomes available for purchase from retiring owners.', 'https://businesswales.gov.wales/socialbusinesswales/mergers-and-acquisition', '4', '[]'), 
('Social Franchising', 'The general concept of Social Franchising concerns replicating a successful Social Business model into new environments. This enables other people who want to achieve the same positive results in their own communities to do so without having to “reinvent the wheel”.', 'https://businesswales.gov.wales/socialbusinesswales/social-franchising', '4', '[]'), 
('Employee Ownership', 'Employee ownership means a significant and meaningful stake in a business for all its employees. If this is achieved then a business has employee ownership: it has employee owners.', 'https://businesswales.gov.wales/socialbusinesswales/employee-ownership', '4', '[{"title":"Simply Buyout: A guide to employee buyouts and becoming an employee owned business.","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Simply%20Buyout.pdf"},{"title":"Co-operative Values and Principles","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/The%20Co-operative%20Principles%20vSBW_0.pdf"}]'), 
('Business Plan', 'As a social business your business plan will differ slightly in focus from that of a more conventional business.', 'https://businesswales.gov.wales/socialbusinesswales/business-plan', '2', '[{"title":"Guide to Business Planning","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Business%20Planning%20vSBW_0.pdf"},{"title":"Budget Template","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Budget%20Template_0_0.xls"},{"title":"Business Plan Template","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Business%20Plan%20template.v4_0.docx"}]'), 
('The structure of a Social Business', 'At some point in the start up process, you will need to create a new legal vehicle for your social business.', 'https://businesswales.gov.wales/socialbusinesswales/structure-social-business', '2', '[{"title":"The types of Social Business","URL":"https://businesswales.gov.wales/socialbusinesswales/types-social-business"},{"title":"The legal form of a Social Business","URL":"https://businesswales.gov.wales/socialbusinesswales/legal-form-social-business"},{"title":"Charitable status of a Social Business","URL":"https://businesswales.gov.wales/socialbusinesswales/charitable-status-social-business"},{"title":"Choosing the structure of a Social Business","URL":"https://businesswales.gov.wales/socialbusinesswales/choosing-structure-social-business"}]'), 
('Human Resources', 'When starting up a new business proper thought must be put to the recruitment and employment of its people – the human resource.  ', 'https://businesswales.gov.wales/socialbusinesswales/human-resources', '2', '[{"title":"Guide to Employing People","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Employing%20People%20vSBW.pdf"},{"title":"Appendix A-K Model Forms for Employing People","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Appendix%20A-K%20Model%20Forms%20for%20Employing%20People.docx"},{"title":"Appendix L-V Model Employment Policies","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Appendix%20L-V%20Model%20Employment%20Policies.docx"},{"title":"Appendix X (1-39) Template Letters and Forms","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Appendix%20X%20%281-39%29%20Template%20Letters%20and%20Forms.docx"},{"title":"Appendix Y (1-9) Employment Process Flowcharts","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Appendix%20Y%20%281-10%29%20-%20Employment%20Process%20Flow%20Charts.pdf"}]'), 
('Project Management', 'Creating a new business or undertaking change in an existing business is a project which requires co-ordination and effective co-ordination of design and implementation.', 'https://businesswales.gov.wales/socialbusinesswales/project-management', '2', '[]'), 
('Sources of Finance', '', 'https://businesswales.gov.wales/socialbusinesswales/sources-finance', '2', '[]'), 
('Lenders', 'The following are links to suitable lenders that are familiar in dealing with Social Businesses. However, with a strong business plan and a strong team, do not rule out the possibility of approaching traditional high street banks.', 'https://businesswales.gov.wales/socialbusinesswales/lenders', '2', '[]'), 
('Books and Online Resources', '', 'https://businesswales.gov.wales/socialbusinesswales/books-and-online-resources', '2', '[{"title":"Co-operative Loan Agreement Template","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Co-operative%20Loan%20Agreement%20template%20v4_0.docx"}]'), 
('Social Business Governance Zone', 'Social Businesses are at the forefront of the development of good governance, combining as they do the requirements to provide the governance functions of commercial businesses and organisations providing benefit to Members or some community.', 'https://businesswales.gov.wales/socialbusinesswales/social-business-governance-zone', '3', '[{"title":"Download a Governance Questionnaire","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Governance%20Questionnaire%20v4_0.docx"}]'), 
('Developing required Policies', '', 'https://businesswales.gov.wales/socialbusinesswales/developing-required-policies', '3', '[{"title":"Policy Checklist","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Policy_Checklist_v5ac.xls"},{"title":"Guide to Employing People 2015","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Guide%20to%20Employing%20People%20-%202015%20FINAL.pdf"}]'), 
('Meeting Legal Reporting Requirements', 'A Social Business will be established as some kind of legal entity. A legal entity has important rights, most importantly to enter into contracts with suppliers, customers, employees, project partners and the like.', 'https://businesswales.gov.wales/socialbusinesswales/meeting-legal-reporting-requirements', '3', '[{"title":"Download a Guide to Business Compliance for Social Businesses","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Business%20Compliance%20vSBW_0.pdf"}]'), 
('Stakeholder and Membership Engagement', 'One of the great strengths of Social Businesses is that they engage in ownership and influence wider ranges and greater numbers of Stakeholders and Members than most businesses of similar size.', 'https://businesswales.gov.wales/socialbusinesswales/stakeholder-and-membership-engagement', '3', '[]'), 
('Providing Control and Oversight', 'A Social Business, as a legal entity, is a body corporate and must obey all laws, not only the Companies Act or Co-operative Societies Act (or equivalent legislation for the precise legal form taken by the Social Business) but also those that relate to Health and Safety, employment, tax, trade, contracts, finance, equal opportunity, protection of the vulnerable and much, much more.', 'https://businesswales.gov.wales/socialbusinesswales/providing-control-and-oversight', '3', '[]'), 
('Developing Governance Capacity', 'A fundamental component of success for a Social Business is the strength of its Governance. Governance is the systems and processes concerned with ensuring the overall direction, supervision and accountability of an organisation.', 'https://businesswales.gov.wales/socialbusinesswales/developing-governance-capacity', '3', '[{"title":"Download a Governance Questionnaire","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Governance%20Questionnaire%20v4_0_0.docx"}]'), 
('Business Planning for a Social Business', '', 'https://businesswales.gov.wales/socialbusinesswales/business-planning-social-business', '3', '[{"title":"Guide to Business Planning","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Business%20Planning%20vSBW_1.pdf"},{"title":"Download a Business Plan template here","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Business%20Plan%20template.v4_0_0.docx"}]'), 
('Quality Systems for Social Business', 'A Quality System is whatever is needed in any particular Social Business to deliver a quality assured product or service.', 'https://businesswales.gov.wales/socialbusinesswales/quality-systems-social-business', '3', '[]'), 
('Business Planning for a Social Business', '', 'https://businesswales.gov.wales/socialbusinesswales/business-planning-social-business', '3', '[{"title":"Guide to Business Planning","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Business%20Planning%20vSBW_1.pdf"},{"title":"Download a Business Plan template here","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Business%20Plan%20template.v4_0_0.docx"}]'), 
('Financial Control in Social Business', 'In law it is the responsibility of the Board of Directors (or equivalent) to control the business and this includes all spending.', 'https://businesswales.gov.wales/socialbusinesswales/financial-control-social-business', '3', '[]'), 
('Human Resources Development in a Social Business', 'It is important to be clear what the basis of the relationship between a social business and the people who carry out work for it is. Is the worker a partner, a self-employed contractor, a volunteer or a directly paid employee? Are they full time or part time and if part-time is the business the main employer or a secondary employer?', 'https://businesswales.gov.wales/socialbusinesswales/human-resources-development-social-business', '3', '[{"title":"Guide to Employing People","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Employing%20People%20vSBW_0.pdf"},{"title":"Appendix A-K Model Forms for Employing People","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Appendix%20A-K%20Model%20Forms%20for%20Employing%20People.docx"},{"title":"Appendix L-V Model Employment Policies","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Appendix%20L-V%20Model%20Employment%20Policies.docx"},{"title":"Appendix X (1-39) Template Letters and Forms","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Appendix%20X%20%281-39%29%20Template%20Letters%20and%20Forms.docx"},{"title":"Appendix Y (1-9) Employment Process Flowcharts","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Appendix%20Y%20%281-10%29%20-%20Employment%20Process%20Flow%20Charts.pdf"}]'), 
('Marketing for a Social Business', 'The whole understanding of what constitutes “The Market” can be more complex for a Social Business than for others. Generally, business is predicated on the concept of a marketplace in which the consumer is also the purchaser and they make their purchasing decision based on considerations of quality, price and convenience. The range of options and prices at which the product is offered by the supplier is pitched by a calculation of the optimum mix of likely sales volume and profit per item to suit their own capacity and ambition.', 'https://businesswales.gov.wales/socialbusinesswales/marketing-social-business', '3', '[{"title":"Developing a Marketing Strategy","URL":"https://businesswales.gov.wales/socialbusinesswales/developing-marketing-strategy"}]'), 
('Managing Risk in a Social Business', 'The Wales Co-operative Centre has a process that provides it with a systematic view of the risks it faces in the course of activities. As part of this process the Centre establishes a corporate risk register as well as programme, project and function risk registers to identify the risks that the organisation faces, their grading in terms of likelihood of occurring and seriousness of impact and plans for managing each risk.', 'https://businesswales.gov.wales/socialbusinesswales/managing-risk-social-business', '3', '[{"title":"Risk Register Procedure","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Risk%20Register%20Procedure%20v4_0.docx"},{"title":"Risk Register Methodology","URL":"https://businesswales.gov.wales/socialbusinesswales/sites/socialbusiness/files/Risk%20register%20methodology.xls"}]'), 
('Case Studies', 'Examples of social businesses we have worked with across Wales to help grow, expand, diversify, collaborate and transform.', 'https://businesswales.gov.wales/socialbusinesswales/case-studies', '5', '[{"title":"Vi-Ability","description":"UK Social Enterprise of the Year 2015","URL":"https://businesswales.gov.wales/socialbusinesswales/vi-ability"},{"title":"Wild Women Enterprise Co.","description":"Creating prosperity for the Powys rural economy","URL":"https://businesswales.gov.wales/socialbusinesswales/wild-women-enterprise-co"},{"title":"Theatr Soar","description":"Enriching lives in Merthyr through the arts","URL":"https://businesswales.gov.wales/socialbusinesswales/theatr-soar"},{"title":"Ail Gyfle-Second Chance","description":"Engaging ex-offenders to improve their employability","URL":"https://businesswales.gov.wales/socialbusinesswales/ail-gyfle-second-chance"},{"title":"PS Facilities Management","description":"Promoting positive mental health and well-being","URL":"https://businesswales.gov.wales/socialbusinesswales/ps-facilities-management"},{"title":"SPPOT","description":"Supporting people and pets through opportunities and training","URL":"https://businesswales.gov.wales/socialbusinesswales/sppot"},{"title":"Eurosource","description":"Global suppliers of pipeline products ","URL":"https://businesswales.gov.wales/socialbusinesswales/eurosource"},{"title":"Splash Magic Leisure Centre","description":"The community hub alive and kicking","URL":"https://businesswales.gov.wales/socialbusinesswales/splash-magic-leisure-centre"},{"title":"Down to Earth Project","description":"Practical hands on sustainability training","URL":"https://businesswales.gov.wales/socialbusinesswales/down-earth-project"},{"title":"Tyn-Y-Capel Inn & Restaurant","description":"Community owned business","URL":"https://businesswales.gov.wales/socialbusinesswales/tyn-y-capel-inn-restaurant"},{"title":"Allied Construction Consortium Ltd (ACC Ltd)","description":"Stronger together through consortia working","URL":"https://businesswales.gov.wales/socialbusinesswales/allied-construction-consortium-ltd-acc-ltd"}]');


COMMIT;
